#------------------------------------------------#
#                                                #
#             MultiHome Config File              #
#                                                #
#------------------------------------------------#

config:
  teleport-time: 5.0
  language: en-EN
